//
//  UIColor+IWIAdditions.swift
//
//  Generated by Zeplin on 12/21/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var iwiSand: UIColor { 
		return UIColor(red: 227.0 / 255.0, green: 169.0 / 255.0, blue: 100.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var iwiDarkBlue: UIColor { 
		return UIColor(red: 0.0, green: 94.0 / 255.0, blue: 156.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var iwiWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var iwiBlack: UIColor { 
		return UIColor(red: 15.0 / 255.0, green: 16.0 / 255.0, blue: 16.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var iwiSilver: UIColor { 
		return UIColor(red: 223.0 / 255.0, green: 225.0 / 255.0, blue: 229.0 / 255.0, alpha: 1.0)
	}
    
    @nonobjc class var iwiMicButtonShadow: UIColor {
        return UIColor(red: 0.0 / 255.0, green: 0.0 / 255.0, blue: 0.0 / 255.0, alpha: 0.2)
    }

    @nonobjc class var iwiMicSelectedShadow: UIColor {
        return UIColor(red: 102.0 / 255.0, green: 211.0 / 255.0, blue: 243.0 / 255.0, alpha: 0.8)
    }
    
    @nonobjc class var iwiMicImageShadow: UIColor {
        return UIColor(red: 55.0 / 255.0, green: 222.0 / 255.0, blue: 152.0 / 255.0, alpha: 0.38)
    }
	@nonobjc class var iwiCoolGrey: UIColor {
		return UIColor(red: 161.0 / 255.0, green: 162.0 / 255.0, blue: 163.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var iwiMainBlue: UIColor { 
		return UIColor(red: 1.0 / 255.0, green: 109.0 / 255.0, blue: 180.0 / 255.0, alpha: 1.0)
	}
    
    @nonobjc class var iwiChatText: UIColor {
        return UIColor(red: 16.0 / 255.0, green: 16.0 / 255.0, blue: 16.0 / 255.0, alpha: 1.0)
    }

    @nonobjc class var iwiButtonSelected: UIColor {
        return UIColor(red: 216.0 / 255.0, green: 156.0 / 255.0, blue: 84.0 / 255.0, alpha: 1.0)
    }

	@nonobjc class var iwiWhite60: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.6)
	}
}
